<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cgm" nsURI="http://www.arsysop.ru/cast/cgm/0.1.0" nsPrefix="cgm">
  <eClassifiers xsi:type="ecore:EClass" name="CompilationSession">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tool" lowerBound="1" eType="#//Tool"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" lowerBound="1"
        eType="#//Options"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1" eType="#//Index"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" eType="#//CallTree"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="clang"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Options"/>
  <eClassifiers xsi:type="ecore:EClass" name="Index"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallTree"/>
</ecore:EPackage>
