<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="decl" nsURI="http://www.arsysop.ru/cast/decl/0.1.0" nsPrefix="decl">
  <eClassifiers xsi:type="ecore:EClass" name="CompilationSession">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tool" lowerBound="1" eType="#//Tool"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" lowerBound="1"
        eType="#//Options"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1" eType="#//Index"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="clang"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Options"/>
  <eClassifiers xsi:type="ecore:EClass" name="Index"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedDecl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TranslationUnitDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//NamedDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//NamedDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassTemplateDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//CxxMethodTemplateDecl" containment="true" eOpposite="#//CxxMethodTemplateDecl/classTemplate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CxxMethodTemplateDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classTemplate" lowerBound="1"
        eType="#//ClassTemplateDecl" eOpposite="#//ClassTemplateDecl/methods"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDecl" eSuperTypes="#//NamedDecl"/>
</ecore:EPackage>
