<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cast" nsURI="http://www.arsysop.ru/cast/0.1.0" nsPrefix="cast">
  <eClassifiers xsi:type="ecore:EClass" name="NamedDecl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TranslationUnitDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//NamedDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//NamedDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassTemplateDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//FunctionDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDecl" eSuperTypes="#//NamedDecl"/>
</ecore:EPackage>
